// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUAv6WINttL3IyEGiqcn7SrTkLJC6vf0Q',
    appId: '1:498696658802:web:2d05ebd188b69aead307eb',
    messagingSenderId: '498696658802',
    projectId: 'wyddb23-259fe',
    authDomain: 'wyddb23-259fe.firebaseapp.com',
    storageBucket: 'wyddb23-259fe.appspot.com',
    measurementId: 'G-S4L1B0VNLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKQ4RZAxYyQifSY30HtrTis99DrpSgSBY',
    appId: '1:498696658802:android:f7a753865d71aea8d307eb',
    messagingSenderId: '498696658802',
    projectId: 'wyddb23-259fe',
    storageBucket: 'wyddb23-259fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3PkE5BMPkQE5-nwFfckrARwgVeqhOavM',
    appId: '1:498696658802:ios:b181e1c8cf52aa03d307eb',
    messagingSenderId: '498696658802',
    projectId: 'wyddb23-259fe',
    storageBucket: 'wyddb23-259fe.appspot.com',
    iosClientId: '498696658802-60f1ptucssb9ajospi4pupragegpskol.apps.googleusercontent.com',
    iosBundleId: 'com.example.wyddb23Flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3PkE5BMPkQE5-nwFfckrARwgVeqhOavM',
    appId: '1:498696658802:ios:eb0228b1e54315e7d307eb',
    messagingSenderId: '498696658802',
    projectId: 'wyddb23-259fe',
    storageBucket: 'wyddb23-259fe.appspot.com',
    iosClientId: '498696658802-csitbkqnp1f1t9c61ggdjm3ofdmcdteg.apps.googleusercontent.com',
    iosBundleId: 'com.example.wyddb23Flutter.RunnerTests',
  );
}
